<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
	  <EnableMsixTooling>true</EnableMsixTooling>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <PackageIcon>logo.ico</PackageIcon>
    <IncludeSymbols>False</IncludeSymbols>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

 

  <ItemGroup>
    <PackageReference Include="FastReport.OpenSource" Version="2024.1.10" />
    <PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2024.1.10" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageReference Include="netDxf" Version="2023.11.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NPOI" Version="2.7.2" />
    <PackageReference Include="Pdfium.Net.SDK" Version="4.96.2704" />
    <PackageReference Include="RtfPipe" Version="2.0.7677.4303" />
    <PackageReference Include="Spire.PDF" Version="11.4.10" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\ApiService\ApiService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CustomControls\CustomTextBoxTarih.cs" />
    <Compile Update="CustomControls\CustomTextBoxSayisal.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Formlar\Genel\MalzemeAltGrup2TanimFormu.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Formlar\Genel\MalzemeAltGrupTanimFormu.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Formlar\Genel\MalzemeGrupTanimFormu.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Formlar\MainWindow.cs" />
    <Compile Update="Formlar\Satinalma\Teklif\SatinalmaTekliflerFormu.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Formlar\Satis\SatisSiparisTeklifTalepKayitFormu.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Formlar\Satis\SatisSiparisTeklifTalepGridForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Formlar\Stok\StokKartGridForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="CustomControls\CustomComboListBox.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Formlar\Satis\SatisSiparisTeklifTalepGridForm.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Formlar\Satinalma\Siparis\" />
    <Folder Include="Properties\DataSources\" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\yektamak-118\.nuget\packages\pdfium.net.sdk\4.96.2704\build\..\content\libpdfium.dylib" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\yektamak-118\.nuget\packages\pdfium.net.sdk\4.96.2704\build\..\content\libpdfium.dylib" />
  </ItemGroup>

  

  

</Project>