<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <Compile Remove="wwwroot\css\bootstrap\**" />
    <Content Remove="Services\**" />
    <Content Remove="wwwroot\css\bootstrap\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="wwwroot\css\bootstrap\**" />
    <None Remove="Services\**" />
    <None Remove="wwwroot\css\bootstrap\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\ApiService\ApiService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="WebUIGlobals\Global\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="3.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
    <PackageReference Include="NPOI" Version="2.7.3" />
  </ItemGroup>

</Project>
